lsi: false
safe: true
source: /
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
title: Tutorial
description: Tutorials written by t-tkht.
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
