lsi: false
safe: true
source: /
incremental: false

gist:
  noscript: false

# More › http://kramdown.gettalong.org/quickref.html
# Options › http://kramdown.gettalong.org/options.html
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

  # enable_coderay: true
  # coderay_line_number_start: 1
  # coderay_line_numbers: table

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  # syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    # css_class: 'highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    # span:
    #   line_numbers: false
    # block:
    #   line_numbers: true
    #   start_line: 1

title: Tutorial
description: Tutorials written by t-tkht.
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker

exclude:
  README.md
